name: Train Model like artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/model/train.py'

jobs:
  train_model:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        lr: [1e-3, 3e-4]
        batch: [64, 128]
        hidden: ["64 64", "128 64", "256 128"]
        epochs: [50]  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      id: setup
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run train.py
      run: python src/model/train.py --IdExecution ${{ github.run_number }}